apiVersion: v1
kind: Service
metadata:
  name: cfl-ctf-svc
  namespace: default
spec:
  ports:
    - name: myport
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: cfl-ctf-challenge-2025
  type: ClusterIP
